# Generated by Django 5.2.17 on 2026-08-23 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('subtitle', models.TextField(blank=True, default='')),
                ('badge_text', models.CharField(blank=True, default='', max_length=150)),
                ('placement', models.CharField(choices=[('HOME_HERO', 'Home Hero Banner'), ('VELORA_HERO', 'Velora Hero Banner'), ('ELAN_HERO', 'Elan Hero Banner'), ('STRYDE_HERO', 'Stryde Hero Banner'), ('PROMO_STRIP', 'Promotional Strip Banner'), ('OFFER_POPUP', 'Offer Popup Banner')], default='HOME_HERO', max_length=50)),
                ('image_url', models.CharField(max_length=500)),
                ('button_primary_text', models.CharField(blank=True, default='', max_length=100)),
                ('button_primary_link', models.CharField(blank=True, default='', max_length=255)),
                ('button_secondary_text', models.CharField(blank=True, default='', max_length=100)),
                ('button_secondary_link', models.CharField(blank=True, default='', max_length=255)),
                ('button_tertiary_text', models.CharField(blank=True, default='', max_length=100)),
                ('button_tertiary_link', models.CharField(blank=True, default='', max_length=255)),
                ('background_color', models.CharField(blank=True, default='#0f172a', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['display_order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='RONAQ', max_length=150)),
                ('site_tagline', models.CharField(default='Luxury Collective', max_length=255)),
                ('site_description', models.TextField(default='Ronaq is a premier luxury collective bringing together three distinct worlds of cosmetics, fashion, and athletic footwear under one standard of elegance.')),
                ('logo_url', models.CharField(blank=True, default='', max_length=500)),
                ('custom_logo_text', models.CharField(blank=True, default='RONAQ', max_length=100)),
                ('subbrand_velora_tagline', models.CharField(default='Cosmetics & Skincare', max_length=100)),
                ('subbrand_elan_tagline', models.CharField(default='Luxury Apparel', max_length=100)),
                ('subbrand_stryde_tagline', models.CharField(default='Athletic Footwear', max_length=100)),
                ('announcement_enabled', models.BooleanField(default=True)),
                ('announcement_text', models.CharField(default='🎉 FREE EXPRESS COURIER SHIPPING on all orders over $50 across Pakistan', max_length=255)),
                ('announcement_badge', models.CharField(default='SPECIAL OFFER', max_length=100)),
                ('announcement_link', models.CharField(default='/velora', max_length=255)),
                ('top_welcome_text', models.CharField(default='Welcome to RONAQ — House of Premium Brands', max_length=255)),
                ('phone_number', models.CharField(default='+92 300 1234567', max_length=50)),
                ('phone_display', models.CharField(default='1-800-RONAQ', max_length=50)),
                ('whatsapp_number', models.CharField(default='+92 300 1234567', max_length=50)),
                ('whatsapp_message', models.CharField(default='Hello! I am inquiring about products on Ronaq.', max_length=300)),
                ('whatsapp_floating_enabled', models.BooleanField(default=True)),
                ('email', models.EmailField(default='support@ronaq.com', max_length=150)),
                ('address', models.CharField(default='Ronaq Luxury HQ, Lahore, Pakistan', max_length=255)),
                ('free_shipping_threshold', models.DecimalField(decimal_places=2, default=50.0, max_digits=10)),
                ('currency_symbol', models.CharField(default='$', max_length=10)),
                ('instagram_url', models.CharField(blank=True, default='https://instagram.com', max_length=255)),
                ('facebook_url', models.CharField(blank=True, default='https://facebook.com', max_length=255)),
                ('twitter_url', models.CharField(blank=True, default='https://twitter.com', max_length=255)),
                ('youtube_url', models.CharField(blank=True, default='https://youtube.com', max_length=255)),
                ('home_hero_title', models.CharField(default='One Destination. Three Iconic Sub-Brands.', max_length=255)),
                ('home_hero_subtitle', models.TextField(default='Experience Velora skincare, Elan luxury apparel, and Stryde athletic footwear under Ronaq’s unified multi-brand house.')),
                ('home_hero_badge', models.CharField(default='The Premier Luxury Umbrella Brand', max_length=150)),
                ('home_hero_image', models.CharField(default='https://images.unsplash.com/photo-1441986300917-64674bd600d8?auto=format&fit=crop&w=2000&q=80', max_length=500)),
                ('velora_hero_title', models.CharField(default='Velora Cosmetics & Skincare', max_length=255)),
                ('velora_hero_subtitle', models.TextField(default='Pure, dermatologically tested skincare and luminous makeup formulas crafted for glowing, healthy skin.')),
                ('velora_hero_badge', models.CharField(default='Sub-Brand Spotlight', max_length=150)),
                ('velora_hero_image', models.CharField(blank=True, default='', max_length=500)),
                ('elan_hero_title', models.CharField(default='Elan Luxury Apparel & Fashion', max_length=255)),
                ('elan_hero_subtitle', models.TextField(default='Bespoke tailoring, signature ready-to-wear silhouettes, and timeless couture created for the modern connoisseur.')),
                ('elan_hero_badge', models.CharField(default='Haute Couture Collection', max_length=150)),
                ('elan_hero_image', models.CharField(blank=True, default='', max_length=500)),
                ('stryde_hero_title', models.CharField(default='Stryde Performance & Athletic Footwear', max_length=255)),
                ('stryde_hero_subtitle', models.TextField(default='High-performance engineering, responsive cushioning, and sleek urban aesthetics built for all-day motion.')),
                ('stryde_hero_badge', models.CharField(default='Athletic Innovation', max_length=150)),
                ('stryde_hero_image', models.CharField(blank=True, default='', max_length=500)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
            },
        ),
    ]
